# Generated by Django 2.1.15 on 2020-01-18 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('emp_first_name', models.CharField(max_length=20)),
                ('emp_last_name', models.CharField(max_length=20)),
                ('emp_gender', models.CharField(max_length=20)),
                ('emp_email', models.CharField(max_length=20)),
                ('emp_dob', models.DateField()),
                ('emp_marital_status', models.CharField(max_length=20)),
                ('emp_home_number', models.CharField(max_length=20)),
                ('emp_personal_number', models.CharField(max_length=20)),
                ('emp_hire_date', models.DateField()),
                ('emp_designation', models.CharField(max_length=20)),
                ('emp_type', models.CharField(max_length=20)),
                ('emp_address', models.CharField(max_length=20)),
                ('emp_city', models.CharField(max_length=20)),
                ('emp_state', models.CharField(max_length=20)),
                ('emp_postal_code', models.CharField(max_length=20)),
                ('emp_country', models.CharField(max_length=20)),
                ('emp_notes', models.CharField(max_length=250)),
                ('emp_work_location', models.CharField(max_length=20)),
                ('emp_manager_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=20)),
                ('project_description', models.CharField(max_length=100)),
                ('project_company', models.CharField(max_length=20)),
                ('project_owner', models.CharField(max_length=20)),
                ('project_category', models.CharField(max_length=20)),
                ('project_status', models.CharField(max_length=20)),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('project_budget', models.IntegerField()),
                ('project_summary', models.CharField(max_length=250)),
                ('project_record', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.ProjectDetails'),
        ),
    ]
