# Generated by Django 2.1.15 on 2020-01-25 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('emp_first_name', models.CharField(max_length=20)),
                ('emp_last_name', models.CharField(max_length=20)),
                ('emp_gender', models.CharField(max_length=20)),
                ('emp_email', models.CharField(max_length=20)),
                ('emp_dob', models.DateField()),
                ('emp_marital_status', models.CharField(max_length=20)),
                ('emp_home_number', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_personal_number', models.CharField(max_length=20)),
                ('emp_hire_date', models.DateField()),
                ('emp_designation', models.CharField(max_length=20)),
                ('emp_type', models.CharField(max_length=20)),
                ('emp_address', models.CharField(max_length=20)),
                ('emp_city', models.CharField(max_length=20)),
                ('emp_state', models.CharField(max_length=20)),
                ('emp_postal_code', models.CharField(max_length=20)),
                ('emp_country', models.CharField(max_length=20)),
                ('emp_notes', models.CharField(blank=True, max_length=250, null=True)),
                ('emp_work_location', models.CharField(max_length=20)),
                ('emp_manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=20)),
                ('project_description', models.CharField(blank=True, max_length=100, null=True)),
                ('project_company', models.CharField(max_length=20)),
                ('project_owner', models.CharField(max_length=20)),
                ('project_category', models.CharField(max_length=20)),
                ('project_status', models.CharField(max_length=20)),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField(blank=True, null=True)),
                ('project_budget', models.IntegerField()),
                ('project_summary', models.CharField(blank=True, max_length=250, null=True)),
                ('project_record', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logger_name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'NotSet'), (20, 'Info'), (30, 'Warning'), (10, 'Debug'), (40, 'Error'), (50, 'Fatal')], db_index=True, default=40)),
                ('msg', models.TextField()),
                ('trace', models.TextField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logging',
                'verbose_name_plural': 'Logging',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.ProjectDetails'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
